// -------------------------------------------------------------
// 
// File Name: hdlsrc\fil_pid\Controller.v
// Created: 2021-02-01 02:39:57
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 0.0005
// Target subsystem base rate: 0.0005
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        0.0005
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// control_signal                ce_out        0.0005
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Controller
// Source Path: fil_pid/Controller
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Controller
          (clk,
           reset,
           clk_enable,
           error_d,
           ce_out,
           control_signal);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [31:0] error_d;  // sfix32_En16
  output  ce_out;
  output  signed [31:0] control_signal;  // sfix32_En28


  wire signed [47:0] Gain_1_mul_temp;  // sfix48_En50
  wire signed [31:0] Gain_1_out1;  // sfix32_En36
  wire signed [31:0] I_component_out1;  // sfix32_En42
  wire signed [31:0] D_component_out1;  // sfix32_En33
  wire signed [41:0] Sum_add_cast;  // sfix42_En42
  wire signed [41:0] Sum_add_cast_1;  // sfix42_En42
  wire signed [41:0] Sum_add_temp;  // sfix42_En42
  wire signed [41:0] Sum_add_cast_2;  // sfix42_En42
  wire signed [41:0] Sum_add_temp_1;  // sfix42_En42
  wire signed [31:0] Sum_out1;  // sfix32_En34
  wire signed [31:0] dtc_out;  // sfix32_En28
  wire signed [31:0] Saturation_out1;  // sfix32_En28


  assign Gain_1_mul_temp = 16'sb0100001100011100 * error_d;
  assign Gain_1_out1 = Gain_1_mul_temp[45:14];



  I_component u_I_component (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .In1(error_d),  // sfix32_En16
                             .Out1(I_component_out1)  // sfix32_En42
                             );

  D_component u_D_component (.clk(clk),
                             .reset(reset),
                             .enb(clk_enable),
                             .In1(error_d),  // sfix32_En16
                             .Out1(D_component_out1)  // sfix32_En33
                             );

  assign Sum_add_cast = {{4{Gain_1_out1[31]}}, {Gain_1_out1, 6'b000000}};
  assign Sum_add_cast_1 = {{10{I_component_out1[31]}}, I_component_out1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign Sum_add_cast_2 = {D_component_out1[31], {D_component_out1, 9'b000000000}};
  assign Sum_add_temp_1 = Sum_add_temp + Sum_add_cast_2;
  assign Sum_out1 = Sum_add_temp_1[39:8];



  assign dtc_out = {{6{Sum_out1[31]}}, Sum_out1[31:6]};



  assign Saturation_out1 = (dtc_out > 32'sb01111111111111111001011100100100 ? 32'sb01111111111111111001011100100100 :
              (dtc_out < 32'sb10000000000000000110100011011100 ? 32'sb10000000000000000110100011011100 :
              dtc_out));



  assign control_signal = Saturation_out1;

  assign ce_out = clk_enable;

endmodule  // Controller

