// -------------------------------------------------------------
// 
// File Name: hdlsrc\fil_pid\D_component.v
// Created: 2021-02-01 02:39:57
// 
// Generated by MATLAB 9.9 and HDL Coder 3.17
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: D_component
// Source Path: fil_pid/Controller/D_component
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module D_component
          (clk,
           reset,
           enb,
           In1,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [31:0] In1;  // sfix32_En16
  output  signed [31:0] Out1;  // sfix32_En33


  wire signed [47:0] Gain_3_mul_temp;  // sfix48_En52
  wire signed [31:0] Gain_3_out1;  // sfix32_En38
  reg signed [31:0] Unit_Delay_2_out1;  // sfix32_En38
  wire signed [32:0] Sum2_sub_cast;  // sfix33_En38
  wire signed [32:0] Sum2_sub_cast_1;  // sfix33_En38
  wire signed [32:0] Sum2_sub_temp;  // sfix33_En38
  wire signed [31:0] Sum2_out1;  // sfix32_En48
  wire signed [47:0] Gain_5_mul_temp;  // sfix48_En48
  wire signed [31:0] Gain_5_out1;  // sfix32_En33


  assign Gain_3_mul_temp = 16'sb0101000010001000 * In1;
  assign Gain_3_out1 = Gain_3_mul_temp[45:14];



  always @(posedge clk or posedge reset)
    begin : Unit_Delay_2_process
      if (reset == 1'b1) begin
        Unit_Delay_2_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay_2_out1 <= Gain_3_out1;
        end
      end
    end



  assign Sum2_sub_cast = {Gain_3_out1[31], Gain_3_out1};
  assign Sum2_sub_cast_1 = {Unit_Delay_2_out1[31], Unit_Delay_2_out1};
  assign Sum2_sub_temp = Sum2_sub_cast - Sum2_sub_cast_1;
  assign Sum2_out1 = {Sum2_sub_temp[21:0], 10'b0000000000};



  assign Gain_5_mul_temp = 16'sb0100111000100000 * Sum2_out1;
  assign Gain_5_out1 = Gain_5_mul_temp[46:15];



  assign Out1 = Gain_5_out1;

endmodule  // D_component

